sonar.projectKey=llimona-org_azure-openai
sonar.organization=llimona-org
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest.xml
sonar.sources=src/
sonar.tests=tests/
sonar.coverage.exclusions=tests/**
sonar.python.version=3.14