name: Common make release

on:
  workflow_call:
    inputs:
      level:
        description: "Version increase level"
        required: false
        default: "none"
        type: string

      environment:
        description: "Release environment (e.g. pypi, testpypi, etc.)"
        required: false
        default: "pypi"
        type: string

      pypi-github-token:
        description: "PyPI Github token"
        required: true
        type: string
jobs:
  release:
    name: Make release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: https://pypi.org/project/llimona-azure-openai/

    permissions:
      contents: write
      id-token: write
      pull-requests: none

    outputs:
      version: ${{ steps.define-version.outputs.version }}
      base-release-version: ${{ steps.define-version.outputs.release-patch}}
      release-ref: release/${{ steps.define-version.outputs.release-minor }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-repo

      - uses: ./.github/actions/versioning
        id: define-version
        with:
          level: ${{ inputs.level }}

      - name: Build package
        run: |
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

          
      - name: Make release
        id: make_release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: v${{ steps.define-version.outputs.version-no-build }}
          RELEASE_TITLE: Release ${{ steps.define-version.outputs.version }}
        run: |
          gh release create $TAG_NAME --target ${{ github.sha }} -t "$RELEASE_TITLE" ${{ (inputs.level != 'none') && '--prerelease' || '' }} --generate-notes
          gh release upload $TAG_NAME dist/* --clobber
          echo "release=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "**Tag:** [$TAG_NAME]("$(gh release view $TAG_NAME --json url --jq ".url")")" >> $GITHUB_STEP_SUMMARY

  bump-version:
    name: Bump version
    needs: release

    permissions:
      contents: write
      pull-requests: write
      id-token: none

    if:
      github.ref_name == needs.release.outputs.release-ref && inputs.level == 'none'
    uses: ./.github/workflows/common_push_version.yaml
    with:
      ref: ${{ github.ref_name }}
      level: 'patch'
