name: Manual make release

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Release level"
        required: true
        type: choice
        default: dev
        options:
          - production
          - rc
          - beta
          - alpha
          - dev

jobs:
  make-release:
    name: Make release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: none
      contents: write
      id-token: write
    environment:
        name: pypi-${{ inputs.level == 'production' && 'manual' || 'dev' }}
        url: https://pypi.org/project/llimona/  
    outputs:
      version: ${{ steps.make_release.outputs.version }}
      base-release-version: ${{ steps.make_release.outputs.base-release-version }}
      release-ref: ${{ steps.make_release.outputs.release-ref }}

    steps:
      - if: ${{ inputs.level == 'production' && !startsWith(github.ref_name, 'release/') }}
        name: Check release branch when making production release
        run: |
          echo "# :boom::fire: Production releases must be made from a release branch. Please create a branch named release/x.y from main and push it before running this workflow. :fire::boom:" >> $GITHUB_STEP_SUMMARY
          exit 1
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: ./.github/actions/publishing
        id: make_release
        with:
          level: ${{ inputs.level == 'production' && 'none' || inputs.level }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  bump-version:
    name: Bump version
    needs: make-release

    permissions:
      contents: write
      pull-requests: write
      id-token: none

    if:
      github.ref_name == needs.make-release.outputs.release-ref && inputs.level == 'production'
    uses: ./.github/workflows/common_push_version.yaml
    with:
      ref: ${{ github.ref_name }}
      level: 'patch'
    secrets:
      ACTIONS_GITHUB_TOKEN_PULL_REQUEST: ${{ secrets.ACTIONS_GITHUB_TOKEN_PULL_REQUEST }}
